version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ajudaa
      POSTGRES_PASSWORD: ajudaa
      POSTGRES_DB: ajudaadb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"